version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: promiedosApi
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: promiedosApi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: