version: '3.6'

services:
  supabase-db:
    image: supabase/postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pr0m13d0s4p1
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres.nqeoskqtocqcyrfdquyw
    volumes:
      - supabase-data:/var/lib/postgresql/data

volumes:
  supabase-data:
